//#/types, 2
#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : enable

#include "prelude.h"

//layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer a { readonly TYPE_0 inData[]; };
layout(set = 0, binding = 1) buffer b { writeonly TYPE_1 outData[]; };

void main(){
    outData[gl_GlobalInvocationID.x] = TYPE_1(inData[gl_GlobalInvocationID.x]);
}